---
- name: Ensure facts are gathered
  ansible.builtin.setup:

- name: Install Java if not already installed (RedHat-based)
  ansible.builtin.yum:
    name: java-11-openjdk
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Java if not already installed (Debian-based)
  ansible.builtin.apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install PrettyTable via system package manager (Debian-based)
  ansible.builtin.apt:
    name: python3-prettytable
    state: present
  when: ansible_os_family == "Debian"

- name: Install PrettyTable via system package manager (RedHat-based)
  ansible.builtin.yum:
    name: python3-prettytable
    state: present
  when: ansible_os_family == "RedHat"


- name: Create directory for JMeter
  ansible.builtin.file:
    path: /opt/apache-jmeter
    state: directory
    mode: '0755'

- name: Download Apache JMeter
  ansible.builtin.get_url:
    url: "https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz"
    dest: /opt/apache-jmeter/apache-jmeter-5.6.3.tgz

- name: Extract Apache JMeter
  ansible.builtin.unarchive:
    src: /opt/apache-jmeter/apache-jmeter-5.6.3.tgz
    dest: /opt/apache-jmeter/
    remote_src: yes

- name: Add JMeter to PATH
  ansible.builtin.lineinfile:
    path: /etc/profile.d/jmeter.sh
    line: "export PATH=/opt/apache-jmeter/apache-jmeter-5.6.3/bin:$PATH"
    create: yes
    mode: '0755'

- name: Source JMeter PATH
  ansible.builtin.shell: source /etc/profile.d/jmeter.sh
  args:
    executable: /bin/bash

- name: Upload JMeter test plan
  ansible.builtin.copy:
    src: jmx_files/testetp2.jmx
    dest: /opt/apache-jmeter/apache-jmeter-5.6.3/bin/test_plan.jmx

- name: Run JMeter test
  ansible.builtin.command:
    cmd: >
      /opt/apache-jmeter/apache-jmeter-5.6.3/bin/jmeter -n
      -t /opt/apache-jmeter/apache-jmeter-5.6.3/bin/test_plan.jmx
      -l /opt/apache-jmeter/apache-jmeter-5.6.3/bin/results.jtl
      -Japp_ip={{ app_ip }}
      -Japp_port={{ app_port }}
  register: jmeter_result

#- name: Fetch JMeter results
#  ansible.builtin.fetch:
#    src: /opt/apache-jmeter/apache-jmeter-5.6.3/bin/results.jtl
#    dest: ./results.jtl
#    flat: yes

#- name: Upload Python script to process results
#  ansible.builtin.copy:
#    src: process_results.py
#    dest: /opt/process_results.py
#    mode: '0755'

#- name: Process results into a Summary Report
#  ansible.builtin.shell: python3 /opt/process_results.py ./results.jtl
#  args:
#    executable: /bin/bash
#  register: processed_results

#- name: Display Summary Report
#  ansible.builtin.debug:
#    msg: "{{ processed_results.stdout }}"
