- name: Create a build directory
  ansible.builtin.file:
    path: "{{ docker_build_dir }}"
    state: directory
    mode: "0755"
  when: build is defined and build

- name: Copy Dockerfile to the build directory
  ansible.builtin.copy:
    src: Dockerfile
    dest: "{{ docker_build_dir }}"
    mode: "0644"
  when: build is defined and build

- name: Copy script to the build directory
  ansible.builtin.copy:
    src: moonshotscript.sh
    dest: "{{ docker_build_dir }}"
    mode: "0755"
  when: build is defined and build

- name: Build image from Dockerfile
  community.docker.docker_image:
    name: "{{ moonshot_image }}"
    build:
      path: "{{ docker_build_dir }}"
    source: build
  when: build is defined and build

- name: Run moonshot container
  community.docker.docker_container:
    name: "{{ moonshot_container }}"
    image: "{{ moonshot_image }}"
    state: started
    ports:
      - "8000:8000"
    # env:
    #   DB_HOST: "{{ db_host }}"
    #   DB_DATABASE: "{{ db_name }}"
    #   DB_USERNAME: "{{ db_username }}"
    #   DB_PASSWORD: "{{ db_password }}"
    #   SEED: "true"
    # networks:
    #   - name: "{{ db_network }}"
    detach: true
