apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonshot
  labels:
    app: moonshot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moonshot
  template:
    metadata:
      labels:
        app: moonshot
    spec:
      containers:
        - name: moonshot
          image: "{{ moonshot_image }}"
          env:
            - name: DB_HOST
              value: "{{ db_host }}"
            - name: DB_NAME
              value: "{{ db_name }}"
            - name: DB_USER
              value: "{{ db_username }}"
            - name: DB_PASSWORD
              value: "{{ db_password }}"
            - name: DB_PORT
              value: "5432"

          ports:
            - containerPort: 8000
