apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonshot
  labels:
    app: moonshot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moonshot
  template:
    metadata:
      labels:
        app: moonshot
    spec:
      containers:
        - name: moonshot
          image: "{{ moonshot_image }}"
          env:
            - name: DB_HOST
              value: "{{ db_host }}"
            # - name: DB_DATABASE
            #   value: "{{ db_name }}"
            # - name: DB_USER
            #   value: "{{ db_username }}"
            # - name: DB_PASSWORD
            #   value: "{{ db_password }}"
            - name: POSTGRES_DB
              value: "{{ db_name }}"
            - name: POSTGRES_USER
              value: "{{ db_username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ db_password }}" # aqui ns se ta tudo
          ports:
            - containerPort: 8000
