apiVersion: v1
kind: Service
metadata:
  name: moonshot-service
  labels:
    app: moonshot
  namespace: default
spec:
  type: LoadBalancer # Cria um IP público ou balanceador de carga no provedor de nuvem
  selector:
    app: moonshot
  ports:
    - protocol: TCP
      port: 80 # Porta acessível externamente pelo balanceador de carga
      targetPort: 8000 # Porta no contêiner onde o tráfego será roteado
