apiVersion: v1
kind: Service
metadata:
  name: "{{ moonshot_host }}"
  labels:
    app: moonshot
    tier: app
  namespace: default
spec:
  type: LoadBalancer # Cria um IP público ou balanceador de carga no provedor de nuvem
  selector:
    app: moonshot
  ports:
    - name: http
      protocol: TCP
      targetPort: 8000 # Porta no contêiner onde o tráfego será roteado
      port: { { app_port } } # Porta acessível externamente pelo balanceador de carga
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 7200
